package com.mycompany.skilltest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EvaluationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationAllPropertiesEquals(Evaluation expected, Evaluation actual) {
        assertEvaluationAutoGeneratedPropertiesEquals(expected, actual);
        assertEvaluationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationAllUpdatablePropertiesEquals(Evaluation expected, Evaluation actual) {
        assertEvaluationUpdatableFieldsEquals(expected, actual);
        assertEvaluationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationAutoGeneratedPropertiesEquals(Evaluation expected, Evaluation actual) {
        assertThat(actual)
            .as("Verify Evaluation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationUpdatableFieldsEquals(Evaluation expected, Evaluation actual) {
        assertThat(actual)
            .as("Verify Evaluation relevant properties")
            .satisfies(a -> assertThat(a.getDateEvaluation()).as("check dateEvaluation").isEqualTo(expected.getDateEvaluation()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getMode()).as("check mode").isEqualTo(expected.getMode()))
            .satisfies(a -> assertThat(a.getScoreTotal()).as("check scoreTotal").isEqualTo(expected.getScoreTotal()))
            .satisfies(a -> assertThat(a.getRemarques()).as("check remarques").isEqualTo(expected.getRemarques()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationUpdatableRelationshipsEquals(Evaluation expected, Evaluation actual) {
        assertThat(actual)
            .as("Verify Evaluation relationships")
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()))
            .satisfies(a -> assertThat(a.getTest()).as("check test").isEqualTo(expected.getTest()))
            .satisfies(a -> assertThat(a.getManager()).as("check manager").isEqualTo(expected.getManager()));
    }
}
