package com.mycompany.skilltest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReponseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseAllPropertiesEquals(Reponse expected, Reponse actual) {
        assertReponseAutoGeneratedPropertiesEquals(expected, actual);
        assertReponseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseAllUpdatablePropertiesEquals(Reponse expected, Reponse actual) {
        assertReponseUpdatableFieldsEquals(expected, actual);
        assertReponseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseAutoGeneratedPropertiesEquals(Reponse expected, Reponse actual) {
        assertThat(actual)
            .as("Verify Reponse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseUpdatableFieldsEquals(Reponse expected, Reponse actual) {
        assertThat(actual)
            .as("Verify Reponse relevant properties")
            .satisfies(a -> assertThat(a.getContenu()).as("check contenu").isEqualTo(expected.getContenu()))
            .satisfies(a -> assertThat(a.getEstCorrecte()).as("check estCorrecte").isEqualTo(expected.getEstCorrecte()))
            .satisfies(a -> assertThat(a.getDateReponse()).as("check dateReponse").isEqualTo(expected.getDateReponse()))
            .satisfies(a ->
                assertThat(a.getCommentaireManager()).as("check commentaireManager").isEqualTo(expected.getCommentaireManager())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReponseUpdatableRelationshipsEquals(Reponse expected, Reponse actual) {
        assertThat(actual)
            .as("Verify Reponse relationships")
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()))
            .satisfies(a -> assertThat(a.getEvaluation()).as("check evaluation").isEqualTo(expected.getEvaluation()));
    }
}
