package com.mycompany.skilltest.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestAllPropertiesEquals(Test expected, Test actual) {
        assertTestAutoGeneratedPropertiesEquals(expected, actual);
        assertTestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestAllUpdatablePropertiesEquals(Test expected, Test actual) {
        assertTestUpdatableFieldsEquals(expected, actual);
        assertTestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestAutoGeneratedPropertiesEquals(Test expected, Test actual) {
        assertThat(actual)
            .as("Verify Test auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestUpdatableFieldsEquals(Test expected, Test actual) {
        assertThat(actual)
            .as("Verify Test relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getMode()).as("check mode").isEqualTo(expected.getMode()))
            .satisfies(a -> assertThat(a.getDuree()).as("check duree").isEqualTo(expected.getDuree()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestUpdatableRelationshipsEquals(Test expected, Test actual) {
        assertThat(actual)
            .as("Verify Test relationships")
            .satisfies(a -> assertThat(a.getCompetenceses()).as("check competenceses").isEqualTo(expected.getCompetenceses()));
    }
}
