# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjJkNGQ1ZjM4ZjRhNGU2ZTg2YzFjNTMyMWVhZTc0MjRkZjZkODJmOGYwYmE2MzA5NzUxYTRmZjBhNjkyMmRiNTEyZjc4Y2Y2YmQ3NjkzMzBhOTRmMWQ1YTNlMjA2ZTJjN2YxZWMyNjA2ZTI=
